### PR TITLE
Basic black list is added

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by solomax** [comment]
I believe Black-list init call should be moved to bootstrap ....

**Comment by solomax** [comment]
And the code need to checked for synchronisation issues ...

**Comment by mondain** [comment]
I'll do a once-over when I'm ready to roll-out 1.0.8 final; I think the main requirement there will be jdk8+

**Comment by solomax** [comment]
Any roadmap for the release? Before or after NY? :)

**Comment by mondain** [comment]
I'd like to push it out this week, if time permits

**Comment by solomax** [comment]
Hello @mondain,
Any new estimates for the release?

**Comment by mondain** [comment]
If all goes well, before xmas 12/25

**Comment by solomax** [comment]
Great Xmas present :))
Thanks!

**Pull request merged**
