### PR TITLE
Additional fix for tests

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by mondain** [comment]
I guess the comments don't stay after the merge? Here's where I was hand decoding for AMF0 connect: http://pastebin.com/dhBb1fkU
I think there may be a bug with hasMoreProperties, it shouldn't advance the position if it doesnt find the AMF end object marker.

**Comment by solomax** [comment]
in case hasMoreProperties found "AMF end object marker" it should return false and advance
or caller should skip next 3 bytes

**Comment by mondain** [comment]
Yes, it should skip the marker and return false (I have no more properties); if the marker is not found, the position should return to the start of the check (ie. -3). I would use mark and reset in most cases.

**Comment by solomax** [comment]
OK, so I'll wait for the proper fix :)
Then will try to help with testing :)

**Comment by mondain** [comment]
You've been a big help Max, I am thankful :)

**Comment by mondain** [comment]
I just pushed some changes, but the 0x3f 0xf0 handling doesnt work quite right. I tried parsing it as a header and it kind of worked, but follow up objects were messed up. I did however change the hasMoreProperties to return true if there are less than 3 bytes left, which cant contain an end of object marker. So the only test not working is AMF0Connect

**Pull request merged**
